### PR TITLE
ESM

### LINKED ISSUE #7: Could you provide esm modules and source code without minification as in original ulid package as dist?
I use only one method, but webpack could not do tree shaking on built common module - so the full package code is included in my app instead of some functions

### PR DESCRIPTION
**Pull request by perry-mitchell**
Upgrades the library to ESM.

Closes #7

### CODE REVIEW

**Comment by bluet** [comment]
I'm not sure if this info helps:

I use `rollup` in some of my projects for building to both cjs and esm. Some sample code in `package.json`
```
    "rollup-node": "rollup handler.js --format cjs --file bundle.cjs --environment NODE_ENV:production",
    "rollup:cjs": "rollup -c --environment FORMAT:cjs",
    "rollup:esm": "rollup -c --environment FORMAT:esm",
```

**Comment by perry-mitchell** [comment]
I've built a few ESM+CJS projects recently and they just never seem to work properly from the CJS side. Named imports via Typescript builds done in Webpack etc. don't seem to work properly after switching the base to ESM.

That, and you only really have one type in the package JSON definition: CJS or ESM (module). I don't think dual build libraries are a clean solution and would prefer to just publish ESM, as this is where the community is heading anyhow.

**Comment by perry-mitchell** [comment]
Thanks @bluet - I used your rollup suggestion and it helped a lot. Merging now.

**Comment by perry-mitchell** [comment]
Released `1.0.0-r1` pre-release.

**Pull request merged**
