### PR TITLE
feat: add MIN_ULID and MAX_ULID constants

### PR DESCRIPTION
**Pull request by bradvogel**
Exports new constants `MIN_ULID` and `MAX_ULID`. These can be useful when doing range queries to look for valid ULIDs, eg 

```
id > `${ULID.MIN_ULID} AND id < `${ULID.MAX_ULID}
```

Note: this was also submitted as a PR to the official, yet unmaintained, repo: https://github.com/ulid/javascript/pull/107

### CODE REVIEW

**Review by perry-mitchell — APPROVED** [review]

**Comment by perry-mitchell** [comment]
Looks good! Thanks for this. It'll go out tonight.

**Comment by perry-mitchell** [comment]
Good to note here, however, that using these in a range is not entirely sufficient in testing validity. The `isValid` method should be solely used for that purpose.

If 100% confidence isn't necessary (quick validation or comparison) then this would otherwise be acceptable imo.

**Comment by bradvogel** [comment]
@perry-mitchell Thanks!

**Comment by bradvogel** [comment]
@perry-mitchell Will you release a new version soon?

**Comment by perry-mitchell** [comment]
Released 2.2.0 just now @bradvogel :)

**Pull request merged**
