### PR TITLE
simplify for cloudflare workers

### PR DESCRIPTION
**Pull request by ryan-mars**
-   Fork from ulidx
-   Remove dependencies
-   Remove PRNG detection
-   Web Crypto API only

### CODE REVIEW

**Comment by perry-mitchell** [comment]
@ryan-mars Why fork instead of offering an update to this library to work with cloudflare workers?

**Comment by ryan-mars** [comment]
I don't recall what lead to the decision at the time but it wasn't meant as a slight. Would you like me to submit a PR?

**Comment by perry-mitchell** [comment]
I mean.. I can of course analyse what you changed and can add it to ulidx- was just curious as I created ulidx out of frustration for the lack of support on the original ulid library. If I could help anyone by supporting yet more environments well.. that was my goal.

No offence taken, was just asking :)

**Comment by ryan-mars** [comment]
I'm happy to contribute back. I apologize for creating yet-another-package. It was done out of expedience. I'll look through the code and submit a PR.

The two major differences between Cloudflare Workers and other environments are date seed behavior, and crypto. 

### `Date.now`
From the [Workers' docs](https://developers.cloudflare.com/workers/learning/security-model#step-1-disallow-timers-and-multi-threading):

> In Workers, you can get the current time using the JavaScript Date API, for example by calling `Date.now()`. However, the time value returned by this is not really the current time. Instead, it is the **time at which the network message was received** which caused the application to begin executing. While the application executes, time is locked in place.

### `crypto`
Workers provides the Web Crypto API via `crypto` global. Workers does not run on node. Instead the runtime more resembles a web worker. Thus, using the window shortcut to get the current global scope (instead of self) within a Worker will return an error.

**Comment by perry-mitchell** [comment]
Thanks @ryan-mars for the submitted work - I very much appreciate the gesture.

I can't of course merge this, as it drastically changes the library, removing a lot of the functionality and capability required for other platforms (node, web, web workers etc.). It does give me insight into how you've made it work in Cloudflare workers.

> Workers provides the Web Crypto API via crypto global

This is interesting and something I need to look into. I have issues currently with this due to the Node REPL exposing the same property, and confusing the whole PRNG detection.

> While the application executes, time is locked in place.

This sounds.. absolutely terrible. I don't understand why they'd choose to do this. All the same, I don't know how this library is meant to work when time can't be relied upon. It's a crucial part of the algorithm.

**Comment by perry-mitchell** [comment]
Closing this as I've addressed it in the relevant issue - #5.

**Comment by grempe** [comment]
I just wanted to say thanks to @ryan-mars for creating the fork that works with Workers. I came here to say it since issues/discussions seem to be closed on the fork repo. It's a useful tool for the large community of Workers developers.

🥇 

Cheers.

**Comment by ryan-mars** [comment]
@grempe Thank you so much for the kind feedback. I just want to make something useful to others. I'll make sure issues and discussion are open.

**Pull request closed without merging**
