### PR TITLE
Update package.json exports

### LINKED ISSUE #43: Browser imports broken
https://unpkg.com/ulidx@2.4.0/package.json

As of v2.4.0, the `"browser"` and `"worker"` import conditions are unreachable, because they come after new catchall `"import"` and `"require"` conditions. As a result, browser and worker environments are importing the Node.js bundle and breaking on the `"node:crypto"` import.

```
▲ [WARNING] The package "node:crypto" wasn't found on the file system but is built into node.

  Your Worker may throw errors at runtime unless you enable the "nodejs_compat" compatibility flag. Refer to https://developers.cloudflare.com/workers/runtime-apis/nodejs/ for more details. Imported from:
   - ../../../node_modules/.pnpm/ulidx@2.4.0/node_modules/ulidx/dist/node/index.js


✘ [ERROR] Deployment failed!

  Failed to publish your Function. Got error: Uncaught Error: No such module "node:crypto".
```

I can file a PR now with something that should work without breaking what was fixed in #41.

### PR DESCRIPTION
**Pull request by aaronadamsCA**
This should resolve #43.

I also exported your `package.json` as this is very common in large packages. I don't know _why_, mind you; something to do with bundlers?

### CODE REVIEW

**Comment by aaronadamsCA** [comment]
Oh, this is closest to https://unpkg.com/axios@1.7.3/package.json in case you want to compare. The only difference is the fallback order.

**Comment by perry-mitchell** [comment]
Hi @aaronadamsCA - Thanks for this!

Is there any reason we can't have _node_ as the default? I'd prefer it over having the browser entry there..

**Comment by Dallas62** [comment]
Hello @perry-mitchell, unfortunately all runtime cannot run with the `node:crypto`, in my case, React Native doesn't support it as is.

**Comment by aaronadamsCA** [comment]
@perry-mitchell, yeah, it's for the reason @Dallas62 indicates. Since `"node"` is currently first, it should remain that way to prevent any new problems.

IMO that part's already correct, too, because `"node"` is the exception with `"node:crypto"`, while every other runtime uses the Web Crypto API.

Plus this is all just transitional. In 8 months [Node.js 18 goes EOL](https://github.com/nodejs/release#release-schedule), at which point I'm pretty sure you no longer need a `"node"` build at all! Because `globalThis.crypto` is [stable in Node.js 20](https://nodejs.org/api/webcrypto.html#web-crypto-api). So what you've historically called your `"browser"` build really is your default build now, and only Node.js 16-18 need the `"node"` build for legacy support.

**Comment by Dallas62** [comment]
Any update @perry-mitchell ?

**Review by perry-mitchell — APPROVED** [review]

**Comment by perry-mitchell** [comment]
Released under 2.4.1

**Pull request merged**
